### ISSUE TITLE
No version 1.0.1 available

### ISSUE THREAD

**Issue by scheffield** [igormukhingmailcom/ansible-role-bash_aliases#1]
Hi,

Ansible Galaxy states that there are three versions of this role: 0.1.0, 0.2.0 and 1.0.1. But the last one doesn't exists. The problem is, that `ansible-galaxy` by default tries to fetch the highest version.

Cheers,
Max

**Comment by igormukhingmailcom** [comment]
That was fixed some time ago by adding new (greater) version...
Thanks :)
