### ISSUE TITLE
broken since ansible 2.2?

### ISSUE THREAD

**Issue by fuzzyami** [igormukhingmailcom/ansible-role-bash_aliases#2]
hello! and thanks for this useful code! very handy, but unfortunately broken since 2.2: the with_items command must be (1) wrapped with quotes and (2) curly braces, like jinja2.

so the correct lines are:
with_items: "{{ bash_aliases }}"
and
with_items: "{{ bash_aliases_extra }}"

**Comment by igormukhingmailcom** [comment]
Thanks.
Fixed: https://github.com/ansible-roles/ansible-role-bash_aliases/commit/34e52d7f7e62d4087793fded1bba104c711dbf0f

**Comment by fuzzyami** [comment]
thank you!
